### ISSUE TITLE
Beta Hovercards feature breaks navigation.

### ISSUE THREAD

**Issue by diimdeep** [yayyhb/wikiqwiki#6]
When logged out, clicking will display inline just fine, but when logged in(enabled https://www.mediawiki.org/wiki/Beta_Features/Hovercards ) will navigate to page after click.

**Comment by yayyhb** [comment]
Thanks for the hint, but couldn't reproduce. Nevertheless I will add an note, that Hovercards (Page Previews, when Hovercards are  being released) has to be deactivated. In my opionion, wikiqwiki is an alternate reading enhancement, related to Hoverboards. It makes no sence to have both reading concepts activated at the same time.

**Comment by diimdeep** [comment]
Btw sometime hovercards provide better snippet of content and with picture.

**Comment by yayyhb** [comment]
What do you mean with better? It's nearly the same content. They show the first lines of the article, but without word explenations, like sounding or acronyms (mostly the stuff in brackets). So the only advantage I can see regarding stripping this info is make the text content "look" better. 
IMO this is not necessary, those word explenations might be important when previewing.
I agree for the images. I will consider this for the next major release and will test appearance on inline preview. 
What I mostly don't like about Hovercards is, that the text length is somehow fixed, so it's cut off. I had some articles, which had important content at the end of summary, which was missing in that Hovercard.
And, hover. Hovering a link, breaks the concept of having summaries for summaries :) What was one of the main reason for this extension.
BTW, this popup thing hides content.

**Comment by diimdeep** [comment]
You're right. Great job on making this plugin. 👍
